### ISSUE TITLE
Check doc about b-menu-vert

### ISSUE THREAD

**Issue by lento4ka** [bem/bem-bl#158]
http://bem.github.com/bem-bl/sets/common-desktop/b-menu-vert/b-menu-vert.ru.html

**Comment by afelix** [comment]
https://github.com/bem/bem-bl/pull/159
Не знаю, что где пересобирать (и надо ли) после исправлений. Посмотри pull request, пожалуйста, и реши. :)

**Comment by lento4ka** [comment]
Спасибо!
