### ISSUE TITLE
Рефакторинг b-page

### ISSUE THREAD

**Issue by banzalik** [bem/bem-bl#199]
Сейчас в b-page есть несколько спорных реализаций, хочется их более очевидной реализации.
## b-page.deps.js

``` javascript
{ block: 'i-ua' },
{ block: 'i-jquery', elems: 'core' }
```

это блоки не должны приезжать сразу потому, что 
- использование блока i-ua встречается очень редко
- в b-page явно указан '<!DOCTYPE html>'
- js на странице может полностью отсутствовать
## b-page.bemhtml

``` javascript
cls: 'i-ua_js_no i-ua_css_standard',
```

``` javascript
{
    block: 'i-ua'
},
```

это должно находиться в коде блока i-ua

``` javascript
{
    tag: 'meta',
    attrs: { 'http-equiv': 'X-UA-Compatible', content: 'IE=EmulateIE7, IE=edge' }
},
```

эта часть кода должна быть опциональной

Хочется добиться того, что при структуре bemjson.js:

``` javascript
({
    block: 'b-page',
    title: 'Sometitle',
    head: [{
        elem: 'css',
        url: 'index.css'
    }, {
        elem: 'js',
        url: 'index.js'
    }],
    content: 'Hello Word'
})
```

будут генерироваться файлы 
### index.html

``` html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Sometitle</title>
    <link rel="stylesheet" href="index.css"/>
    <script src="index.js"></script>
</head>
<body class="b-page__body">
    Hello Word
</body>
</html>
```

Где index.css и index.js пустые файлы

**Comment by mcslayer** [comment]
Поддержу Сашу: иногда в проектах нужна именно такая структура, как он описал.

**Comment by vitaliyzolotoy** [comment]
Особенно нужно для верстки промо-страниц.

**Comment by boronchiev** [comment]
> эта часть кода должна быть опциональной

Поддерживаю. Имеет смысл приводить IE8 к IE7?

**Comment by tadatuta** [comment]
Частично реализовано, остальное считаем неактуальным за давностью лет
