### ISSUE TITLE
bemhtml: Single LexicalEnvironment for templates compiled in development mode

### ISSUE THREAD

**Issue by narqo** [bem/bem-bl#215]
When `BEMHTML_ENV` is set to `development`, all templates are live in single LexicalEnvironment createad by the `apply()` function. So local variables defined in one template will affect global variables, that might have been defined earlier.

Here is an example, for the case when we attach compliled `bemhtml.js` to some other module.

In case we have js-module:

``` javascript
// i18n.js
var i18n = function() { /* some code */ };
```

And we want to use this module in our bemhtml templates.

``` javascript
// blah.bemhtml
block blah {
    content: i18n('param')
}
```

But (in case of example) for some reason, we define variable `i18n` in some other template:

``` javascript
// myblock.bemhtml
block myblock {
    default: {
        var i18n = {};
        // hack, hack, hack
    }
```

So with BEMHTML_ENV set as `development`, it will redefine our global `i18n` and will affect _all templates_, not only `myblock`. So code in `blah`'s content will throw an exception.

**Comment by indutny** [comment]
Fixed in 94ac39b7c474233383cf90d9e1ac8b69dfbc1bc8
