### ISSUE TITLE
mix внутри apply-функций отрабатывает не верно

### ISSUE THREAD

**Issue by narqo** [bem/bem-bl#232]
В **0.3** что-то сломалось в обработке моды mix.

Код шаблона

```
block para {

    default, !this.ctx._wrap, !this.elem: {

        apply(
            this._mode = '',
            this.ctx._wrap = true,
            this.ctx = {
                elem: 'inner',
                mix: [{ block: this.block }],
                content: this.ctx
            }
        )

    }

}
```

дает в результате HTML с классом `class="para__inner para__inner"`, вместо ожидаемого `class="para__inner para"`, как в ветке 0.2. 

С `applyWrap()` та же проблема.

Из-за этого, сейчас не правильно отрабатывает шаблон для `b-page`.

**Comment by indutny** [comment]
Пофиксил
