### ISSUE TITLE
i-bem__html: Коллизии в this._.identify()

### ISSUE THREAD

**Issue by narqo** [bem/bem-bl#238]
Метод `this._.identify()` (`bem-bl/blocks-common/i-bem/__html/i-bem__html.bemhtml`) генерирует уникальный идентификатор с привязкой на входной контекст, для которого он был вызван. 

Из-за этого, при нескольких вызовах метода `apply()` одного и того же объекта `BEMHTML`, для разного контекста сгенерируется один и тот же `id`.

```
// blah.bemhtml
// NOTE: generateId: function() { return this._.identify(this.ctx) }
block foo, content: (this.generateId())

block bar, content: (this.generateId())

// blah.priv.js
var BEMHTML = require('blah.bemhtml.js').BEMHTML;

BEMHTML.apply({ block: 'foo' });   // <div class="foo">uniq1</div>   
BEMHTML.apply({ block: 'bar' });   // <div class="bar">uniq1</div>
```

Возможно стоит генерировать `id` с привязкой к объекту `BEMHTML`.

**Comment by narqo** [comment]
Случайно обнаружили, что проблема еще воспроизводится при использовании бандлов: генерируем страницу на сервере, потом подгружаем бандл, в котором есть вызов `this._.identify()`.

**Comment by deeonis** [comment]
Починено и влито в прилинкованном комите
