### ISSUE TITLE
Результат applyNext() не всегда является JS-выражением

### ISSUE THREAD

**Issue by narqo** [bem/bem-bl#243]
Кейс:

```
content: {
    return [applyNext(), 'some-data'];
}
```

В результате компиляции в контенте получим:

```
["", __r68 = this["__$anflg"], this["__$anflg"] = 796985099, __r69 = apply.call(__this), this["__$anflg"] = __r68, "", __r69, 'some-content']
```

т.е. результат `applyNext()` не обернут в `()`. 

При этом `var data = applyNext()` компилируется в `var data = (...);`

**Comment by indutny** [comment]
Починил в https://github.com/veged/ometa-js/commit/a42565e5098c6e52daa035b6f5f1ba537a069811
