### ISSUE TITLE
Possibility to use array as `baseBlock` argument for `decl`

### ISSUE THREAD

**Issue by veged** [bem/bem-bl#255]
We can provide possibility to use array as `baseBlock` for `decl`. This will allow to create some kind of mixins between blocks.

**Comment by arikon** [comment]
@veged А как же базовый принцип вроде «не использовать множественное наследование»? ;)

**Comment by veged** [comment]
@arikon это фактически миксы, которые аналогично работают у нас для css

**Comment by apsavin** [comment]
Может быть, оставить baseBlock как способ указывать непосредственного родителя (от которого будет тянуться цепочка прототипов), а для примесей ввести более явный массив mix?

**Comment by veged** [comment]
@apsavin обратная совместимость никак не ломается, а словом mix это назвать рука не поднимается, т.к. это всё-таки не теже самые миксы, что в БЭМ-дереве

**Comment by apsavin** [comment]
@veged Да, согласен, ложные ассоциации с БЭМ-mix'ами повредят. Можно сделать тогда alias baseBlocks, раз есть возможность передавать массив. 

Тогда получается, что при передаче массива, под капотом должно происходить последовательное наследование блоков-элементов массива, я правильно понимаю?

Если работа еще не ведется по этой фиче, я бы попробовал реализовать и отправить pull request.

**Comment by veged** [comment]
@apsavin мне нравится идея с алиасом

да, по функциональности нужно суммарное наследование, но это не совсем просто, нужно немножко на низком уровне поковыряться с INHERIT и суммированием всего в один объект

если сложности не пугают, будем рады пулреквесту! у самих пока не доходят руки :-(

**Comment by dfilatov** [comment]
Я думаю, что такая цепочка в принципе невозможна. Только главный "класс" и миксы.

**Comment by apsavin** [comment]
Написал пробную [версию](https://github.com/apsavin/bem-bl/commit/a1dd3ce40f53762bcc6aae46a7bb547387393dd1#blocks-common/i-bem/i-bem.js). Вне $.inherit, потому что внутри i-bem реализовано наследование с использованием модификаторов, которое требует наличие `baseBlock`. 

Может быть, стоит добавить в $.inherit возможность определять, что метод вызывается по условию и вынести туда часть, которая про наследование с модификаторами? Функцию, которая определяет, какой метод вызывать (в данном случае `checkMod`) можно записывать в свойства метода. Понятно, что чаще всего такой функционал не требуется, но часть наследования реализовывать в $.inherit, а часть в i-bem тоже не очень привлекательный вариант.

**Comment by veged** [comment]
круто!
правда Дима прямо щас в отпуске, поэтому мы немного попозже посмотрим внимательнее

**Comment by dfilatov** [comment]
В новом bem-core используется версия inherit, которая сама по себе поддерживает миксины. Прикрутить там такое поведение будет несложно.

Меня именно в такой постановке другое смущает -- указание миксинов в baseBlock. Тут есть такой момент: если мы делаем новый блок на основе других блоков, то все вроде бы логично, но когда мы начинаем доопределять уже существующий блок, то там есть некоторые противоречия, например:

``` javascript
 // первая декларация
BEM.DOM.decl('my-block', ...);

// потом, допустим на каком-то уровне переопределения мы хотим доопределить этот же блок и добавить миксин:
BEM.DOM.decl({ block : 'my-block', baseBlock : 'my-mixin' });
```

Вот тут появляется странное: что тут имелось ввиду? Перекрыть все поведение, сделав my-mixin базовым блоком или только добавить миксин?

Поэтому я предлагаю для миксинов добавить отдельное слово в декларации. Как уже писалось выше, mix плохое слово из-за ассоциаций с BEM-миксами. Может тогда тупо mixin?

**Comment by veged** [comment]
кстати у нас сейчас существует эта же неоднозначность -- как мы её разруливаем?

**Comment by dfilatov** [comment]
Сейчас нет неоднозначности -- оно однозначно трактуется как указание нового базового блока для декларируемой сущности. А вот, в случае добавление миксинов в baseBlock, эта неоднозначность появляется.

**Comment by apsavin** [comment]
О да, я рад, что все-таки возвращаемся к решению отделить baseBlock от mixin's. 

Сделать pull-request с новой версией inherit и mixin(s?) в качестве ключевого слова? Или хотите сами уже этим заняться?

**Comment by dfilatov** [comment]
Я думаю, что мы это сделаем в рамках bem-core. Надо только определиться с синтаксисом.

**Comment by apsavin** [comment]
А обновления из bem-core когда-нибудь попадут в bem-bl? Или вы хотите в будущем заменить bem-bl на набор узко специализированных библиотек?

**Comment by veged** [comment]
мне не очень нравится слово `mixin`, давайте назовём `baseMix` — это больше отражает смысл

**Comment by dfilatov** [comment]
А что отражает `base` в `baseMix`? В чем тут "базовость"?

**Comment by veged** [comment]
ну за "наследование" у нас отвечает слово `base`, тут же мы как раз делаем так, что наследование происходит от нескольких блоков -- для обычного наследования уже есть `baseBlock` и в дополнение к нему будет `baseMix` (и видно их смысловую близость)

**Comment by dfilatov** [comment]
Ну ок, `baseMix` так `baseMix`.

**Comment by dfilatov** [comment]
С использованием миксинов для i-bem, кстати, будут всякие проблемы. Ведь, по сути, миксин -- это самодостаточная небольшая примесь, которая добавляют какое-то поведение. Миксин не сможет вмешиваться в основное поведение блока, например, в цепочку реакций на установку модификаторов, он сможет только полностью заместить ее. Либо надо как-то переосмыслить как могут вести себя такие миксины, например, может им стоит тоже давать звать __base, который будет продолжать звать одноименный метод из основного поведения блока. Но это уже может начать взрывать мозг. Либо, если одноименный метод есть и в миксине и в основной декларации блока, то автоматически делать после вызова метода миксина вызов метода из основной декларации блока. Но тут будет вопрос, что делать, если такой метод возвращает какое-то значение.

**Comment by veged** [comment]
@dfilatov я исходил из того, что `baseMix` работает полностью как `baseBlock` в том что касается логики переопределения и вызовов `this.__base()` -- это с одной стороны однозначно, с другой в реальности там программировать такие пересечения не должно возникать желания

**Comment by apsavin** [comment]
Я в некоторых проектах (на Backbone) использую миксины, которые могут вызывать `__base` в своих методах (и их методы можно вызывать через `__base`, если далее в цепочке наследования у класса есть одноименные методы). Это практически никогда не используется, конечно, но выглядит естественно, мозг не взрывает. Более того, поведение, отличное от этого, мной воспринималось бы как некорректное.

**Comment by dfilatov** [comment]
А если подмешиваются два миксина, у которых есть один и тот же метод? Если второй миксин в таком методе зовет `__base` -- будет вызван метод из предыдущего миксина?

**Comment by apsavin** [comment]
В случае, о котором я писал выше, миксины подмешиваются последовательно, так что да, будет. Там другая особенность: нельзя создать "экземпляр миксина".

**Comment by dfilatov** [comment]
Сделал в bem-core baseMix с последовательным встраиванием их в цепочку: базовый блок -> микс1 -> ... -> миксN -> декларация. Каждый микс может звать `__base` в своих методах.
Но, есть ограничение: микс не может сам наследоваться от чего-либо (так как, в этом случае __base в его методах будет указывать на базовый класс самого миксина, а не на класс блока, к которому миксуется). Из-за этого пришлось сделать отдельный метод для декларации миксинов (так как все, что декларируется через decl, имеет базовый класс всегда), сейчас он называется declMix.
У кого какие мнения насчет всего этого?

**Comment by veged** [comment]
мне кажется, что декларирование миксов через отдельный метод рушит всю идею, что смешиваются любые блоки :-( давай подумаем ещё, можно ли как-то сделать так, чтобы проблему с `__base` обойти...

**Comment by dfilatov** [comment]
Я не знаю, можно ли вообще смешивать эти понятия. Чтобы что-то можно было подмешать, это что-то должно быть к этому готово. Иначе вообще непонятно как писать блоки, учитывая что он потом может подмешиваться или не подмешиваться к чему угодно. Но если есть идеи (у меня нет), как можно реализовать такое, то можно обсудить.

**Comment by apsavin** [comment]
Смешивать любые блоки навряд ли получится с такой реализацией наследования, как в i-bem. Ведь декларация блока очень часто разделена на отдельные декларации (например, часть кода, отвечающая за элемент может быть вынесена отдельно), что подразумевает наследование, а наследование, как было отмечено выше, определяет метод `__base`.
Да и нужно ли это на самом деле - смешивать любые блоки? Всегда можно унаследоваться. Общий функционал, определяющий поведение - вынести в миксин.

**Comment by veged** [comment]
я не против того, что блоки подразумевающие смешивание нужно писать внутри как-то по особенному -- но я хотел бы, чтобы это оставались декларации блоков, просто разные внутри

**Comment by dfilatov** [comment]
Ну тогда все равно надо в decl как-то указывать явно что мы декларируем именно такую сущность.

**Comment by veged** [comment]
ок, пусть будет `BEM.declMix`

**Comment by qfox** [comment]
Эти mix напоминают mixin(ruby)/trait(php)/etc.

@tadatuta Есть желание портировать в bem-bl? А то можно было бы закрыть уже.

**Comment by tadatuta** [comment]
implemented in `bem-core`, no need for it here
