### ISSUE TITLE
i-bem__dom.js: Отложенная декларация блоков, которые уже появились в DOM-е

### ISSUE THREAD

**Issue by veged** [bem/bem-bl#265]
Сейчас, js-блоки у которых есть class i-bem и onclick, но нет декларации в BEM.blocks не инитятся.
Это вызывает проблемы в таком кейсе: получить html, вставить в dom, асинхронно запросить скрипты для этого html. Получается, что блоки в dom-е появились, а скрипты с декларациями немного задерживаются и не успевают к вызову BEM.DOM.init. В итоге блоки не инитятся.

Предложение такое: каждый раз когда мы видим js-блок, для которого пока нет декларации, не молча пропускать его, а откладывать в специальный кеш. Потом, когда случается какой-то BEM.DOM.decl, который создаёт новый блок (ранее не существовавший в BEM.blocks) доставать из специального кеша увиденных js-блоков без декларации и пытаться его инитить (причём учитывая live).

**Comment by dfilatov** [comment]
Там все-так немного не такое поведение сейчас -- блок без BEM.DOM.decl не пропускается, для него создается пустой BEM.DOM.decl с live=true.

Еще надо понять, что делать, когда ты пытаешься найти такой блок (findBlockInside, например), который будет пропущен таким образом, но для которого еще не случился отложенный BEM.DOM.decl.

**Comment by veged** [comment]
мы же можем по приехавшей декларации для таких блоков делать доопределение, в том числе обрабатывать live особым образом -- если в новой декларации нету live то делать live=false

про форсированное обращение ничего толкового не придумывается :-( предлагаю просто инитить как есть, тут уж ничего не поделать

**Comment by qfox** [comment]
Событие на регистрацию описания нового блока (decl)
Учитывая какой-нибудь флаг, писать в кеш и, по вышеописанному событию, инитить, когда описание появляется?

> что делать, когда ты пытаешься найти такой блок

в кэш писать колбэк и вызывать после инита?

**Comment by dfilatov** [comment]
Исходная задача решается же проще -- вставляем html обычными DOM-методами, а когда приехали declы для этих блоков -- то делаем BEM.DOM.init. Это вроде выглядит логично -- если у тебя есть только html и его нужно показать, но нет для него js -- значит и нужно его просто вставить. А когда уже есть поведение -- то сделать инициализацию.

Меня смущает заведение еще одних внутренних хэшей/массивов блоков (особенно учитывая задачу про хранение всех инстансов определенного блока), которые, опять же нужно будет очищать при уничтожении блоков (ведь такие "подвисшие" блоки могут удаляться раньше чем для них приедут declы).

**Comment by veged** [comment]
согласен

хотя всёравно могут быть проблемы с liveinit-блоками :-(
