### ISSUE TITLE
Собирать jQuery из модулей

### ISSUE THREAD

**Issue by narqo** [bem/bem-bl#269]
В jQuery 1.8 начали развивать идею [модульной сборки](https://github.com/jquery/jquery#how-to-build-your-own-jquery). Это отлично укладывается в БЭМ-архитектуру: `i-jquery__core`, `i-jquery__ajax`, `i-jquery__ dimensions` и пр. Можно начать думать в этом направлении.

Из минусов: теряются преимущества CDN.

**Comment by deeonis** [comment]
@arikon мы до сих пор хотим этого?

**Comment by arikon** [comment]
@deeonis Не думаю
