### ISSUE TITLE
tag mode for elemMod predicate does not work

### ISSUE THREAD

**Issue by arikon** [bem/bem-bl#278]
http://clubs.ya.ru/bem/replies.xml?item_no=1604

**Comment by veged** [comment]
Won't fix.

Modifiers for elements must be described as `elemMods` key in BEMJSON:

```
{
  block: 'b-block',
  content: {
    elem: 'item',
    elemMods: { key: 'value' },
    content: 'text'
  }
}
```

More details in club comments: http://clubs.ya.ru/bem/replies.xml?parent_id=1619&item_no=1604&with_parent=1#reply-bem-1619
