### ISSUE TITLE
i-bem.js: .mod() as shortcut for getMod/setMod

### ISSUE THREAD

**Issue by veged** [bem/bem-bl#285]
`.mod([elem], modName)` -> `.getMod([elem], modName)`
`.mod([elem], modName, modVal)` -> `.setMod([elem], modName, modVal)`

**Comment by dfilatov** [comment]
Еще есть hasMod, который как-то сюда не вписывается. Но можно, конечно, и не учитывать его.

**Comment by veged** [comment]
ага, не учитывать -- просто рядом добавить +1 метод
