### ISSUE TITLE
i-bem__no-conflicts: Возможность в одном рантайме использовать несколько версий css/js

### ISSUE THREAD

**Issue by dfilatov** [bem/bem-bl#290]

**Comment by dfilatov** [comment]
Бранч для задачи: https://github.com/bem/bem-bl/tree/i-bem__no-conflicts

Тестовые проекты:
- prj1: https://github.com/dfilatov/project-stub/tree/prj1 — отсюда грузим prj2
  - запускать `BEM_CONFLICTS_NO=123 bem server -p 8123`
- prj2: https://github.com/dfilatov/project-stub/tree/prj2
  - запускать `BEM_CONFLICTS_NO=321 bem server -p 8321`

В технологию `blocks-common/i-bem/bem/techs/js.js` добавлена реакция на переменную среды `BEM_CONFLICTS_NO` (должна равняться версии BEM-рантайма).

На проекте нужно задекларировать зависимость для `b-page.deps.js`:

```
({
    shouldDeps: [
        {
            block: 'i-bem',
            elem: 'dom',
            mods: { conflicts: 'no' }
        }
    ]
})
```

Использовать рантайм определённой версии можно через `_BEM['my-version']`.

Восстанавливать глобальный рантайм в конкретную версию (нужно только для вызова `BEM.decl`) можно через `window.BEM = _BEM['my-version']`.

Текущую версию рантайма можно получить через статическое поле `this.__self.version`.

**Comment by dfilatov** [comment]
Открытые вопросы:
- скоупинг в css при сборке (дописывать `.bem-MY-VERSION` ко всем селекторам)
- функция для инкапсуляции `window.BEM = _BEM['my-version']`
- переименовать `BEM.version` во что-то менее потенциально конфликтующее с существующим кодом блоков (`BEM._CONFLICTS_NO`?)

**Comment by deeonis** [comment]
@dfilatov стоит ли нам это доделывать? Если да — опиши суть задачи, пожалуйста.

**Comment by dfilatov** [comment]
У вас есть реальный заказчик для этого?

**Comment by deeonis** [comment]
@dfilatov нет, только этот таск, висящий больше двух лет
