### ISSUE TITLE
i18n.html: Pass current lang into bemjson.js and bemhtml environment

### ISSUE THREAD

**Issue by arikon** [bem/bem-bl#296]

**Comment by arikon** [comment]
cc @tadatuta

**Comment by arikon** [comment]
Think of passing broader environment, shell environment variables e.g.

**Comment by narqo** [comment]
How would you access this variables within BEMJSON?

BTW: you can get current language code with `BEM.I18N.lang()` method within BEMHTML templates.

**Comment by deeonis** [comment]
Закрываю за давностью лет, мы этого больше не хотим
