### ISSUE TITLE
Improve documentation for i-bem__dom.js

### ISSUE THREAD

**Issue by ignovak** [bem/bem-bl#297]
The js-doc description for `i-bem__dom.js` methods lacks detailed explanaition of methods callbacks.

E.g., in method

```
    on : function(ctx, e, data, fn, fnCtx) {
        // ...
    },
```

I'd like to know what arguments `fn` callback takes.

**Comment by arikon** [comment]
@dfilatov Have a look please

**Comment by qfox** [comment]
+1

**Comment by deeonis** [comment]
Мы сейчас работаем над абсолютно новой версией документации, этот таск закрываю как устаревший-дубликат
