### ISSUE TITLE
Автоматически инициализировать js-блоки по domready

### ISSUE THREAD

**Issue by tenorok** [bem/bem-bl#298]
``` js
mustDeps: [
    { block: 'i-bem', elem: 'dom', mods: { init: 'auto' } }
]
```

**Comment by varya** [comment]
И надо будет добавить документацию по noDeps в блок b-page.

**Comment by narqo** [comment]
Вы же это сделали? ceaa04d767c662061dad9b7d828f514c6d70bfbd

**Comment by tenorok** [comment]
Да, только я сделал пул реквест в ветки 0.3 и master.
Миша говорил, что надо ещё в 0.2 вроде, надо?
