### ISSUE TITLE
Оторвать клиентский i-bem.js в зависимостях b-page.

### ISSUE THREAD

**Issue by banzalik** [bem/bem-bl#321]
i-bem__dom.js приезжает всегда, все зависимости от того, есть ли на странице блоки, его использующие.
Предлагаю:
- оторвать в b-page.deps.js `{ block: 'i-bem', elem: 'dom', mods: { init: 'auto' } }`
- Блокам, которым для работы нужен i-bem.js, задекларировать зависимость от него в соответствующих *.deps.js
- `{ block: 'i-bem', elem: 'dom', mods: { init: 'auto' } }` перенести на уровень project-stub

**Comment by varya** [comment]
Пропиши у себя noDeps, если тебе не нужен. Так дешевле для всех.

**Comment by deeonis** [comment]
Закрываю за давностью лет
