### ISSUE TITLE
i-jquery__inherit: добавить в прототип ссылку родительский прототип

### ISSUE THREAD

**Issue by wtfil** [bem/bem-bl#324]
доступ к родительским методам, через ссылку на прототип быстрей, чем через __base (http://jsperf.com/superclass-vs-base)

**Comment by dfilatov** [comment]
Сделай, чтобы методы, в которых есть supercall, делали хоть что-нибудь полезное, помимо supercallа. Вся разница тут же улетучится.

**Comment by wtfil** [comment]
Добавление ссылки бесплатно, так как она не исключает __base.
Притом, исходя из того, что подмена функции происходит только если в ней есть обращение к __base, то вызов supercall будет означать неподмену функции.
Еще получим бонус при работе с асинхронностью (не будет багов при возвращении старого this)

**Comment by delfrrr** [comment]
Соглсен на счет асинхронности: только что пришлось написать

```
    _request: function (method, resource, data) {
        var __base = this.__base.bind(this),
            _this = this;
        return BEM.blocks['i-user'].uid().then(function (userId) {
            resource = ['users', userId, _this._normalizeResource(resource)].join('/');
            return __base(method, resource, data);
        });
    }

```

**Comment by dfilatov** [comment]
Правильно, ли я понимаю, что вы хотите в случае асинхронности, вы хотите писать код вида:
this.ccылкаНаБазовыйПрототип._request.call(this, method, resource, data);
?

**Comment by wtfil** [comment]
можно и без call 
this.ccылкаНаБазовыйПрототип._request(method, resource, data);

**Comment by wtfil** [comment]
Я ошибся. call надо

**Comment by delfrrr** [comment]
Что-то мне кажется что с call не получится, если метод суперкласа обращается к своему суперкласу

**Comment by dfilatov** [comment]
Да, так не получится

**Comment by deeonis** [comment]
В таком случае закрываю за давностью :)
