### ISSUE TITLE
Add ability to use custom attribute to store block parameters

### ISSUE THREAD

**Issue by alexeykuzmin** [bem/bem-bl#326]
Please add ability to use custom attribute to store block parameters.
Now the only options are "onclick" and "ondblclick" but there is at least one case when any of them cannot be used.

Google Chrome extensions [are not allowed](http://developer.chrome.com/extensions/tut_migration_to_manifest_v2.html#security-checklist) to have inline event handlers in HTML code.
Since that bem-bl cannot be used for their development.

**Comment by veged** [comment]
I propose to change some name (`bem-params`) and use such custom attribute in similar way with `body`-events (https://github.com/bem/bem-bl/blob/master/blocks-common/i-bem/__dom/i-bem__dom.js#L187).

**Comment by alexeykuzmin** [comment]
Wouldn't it be better to use non-standard attribute name like `bem-params` by default?

**Comment by veged** [comment]
No, because performance of native parsing js attributes is better (we don't need to do "eval").

**Comment by alexeykuzmin** [comment]
It sounds reasonable.
But when I tried to figure out how much slower custom attribute usage is, I got a pretty weird results.
Please, take a look: http://jsperf.com/attribute-get-and-eval

**Comment by arikon** [comment]
@alexeykizmin What about IE?

**Comment by alexeykuzmin** [comment]
@arikon I do not have IE on my laptop, but I'll try to find somebody with Windows to run test.

**Comment by alexeykuzmin** [comment]
Oh, I forgot `console.log()` call inside function extracting data from `onclick`, test results are invalid.
Run fixed version, `onclick` is at least 3 times faster (up to 80x in Safari).

**Comment by dfilatov** [comment]
Тесты на jsperf некорректные, там тестируется один элемент и, видимо, повторные вызовы на одной ноде оптимизируются браузером.
Мы тут попробовали для кучи элементов -- там JSON.parse быстрее на порядок. Надо переходить.

**Comment by deeonis** [comment]
It's alreadry done
