### ISSUE TITLE
npm модуль

### ISSUE THREAD

**Issue by wtfil** [bem/bem-bl#349]
Было бы не плохо иметь возможность скачать bem-bl через npm
npm install bem-bl

**Comment by narqo** [comment]
Ты и сейчас можешь сделать `npm install git://github.com/bem/bem-bl.git` Опиши подробнее, чем бы это помогло?

**Comment by wtfil** [comment]
У меня не работает такой способ. И npm install https://github.com/bem/bem-bl.git
Я бы хотел подключать bem-bl к проэкту через npm, так как этот смособ не зависит от системы контроля версий и более простой.

**Comment by wtfil** [comment]
Выше я написал, что не работает. Просто попал на время, когда Гитхаб ответил через 10 мин.
