### ISSUE TITLE
Spelling error

### ISSUE THREAD

**Issue by ruslankerimov** [bem/bem-bl#354]
https://github.com/bem/bem-bl/blob/master/blocks-common/i-ua/i-ua.bemhtml#L11 , but https://github.com/bem/bem-bl/blob/master/blocks-desktop/b-page/b-page.bemhtml#L58

**Comment by apostololeg** [comment]
https://github.com/bem/bem-bl/pull/355

**Comment by deeonis** [comment]
Закрываю за сроком давности
