### ISSUE TITLE
i18n: must work in env without console

### ISSUE THREAD

**Issue by apsavin** [bem/bem-bl#396]
i18n tech files fails in env's without console object.

**Comment by tadatuta** [comment]
А этот коммит https://github.com/bem/bem-bl/commit/02b731c1130d3659f6a0ea380260c47d75ebdff9 не исправил проблему?

**Comment by apsavin** [comment]
Исправил, спасибо. 
Я собирался отправить pull request в мастер, не посмотрел, есть ли правки в ветке 0.3. Раз такое дело, закрываю issue.

**Comment by tadatuta** [comment]
мастером пользоваться не нужно, он давно протух и мы его не прибиваем только потому что духу не хватает. настоятельно рекомендую перейти на `0.3`

**Comment by apsavin** [comment]
Спасибо за совет, я всегда пользовался только 0.3
Есть просто привычка смотреть на мастер как на последний стабильный релиз.
