### ISSUE TITLE
Ссылки на якоря в документации не работают

### ISSUE THREAD

**Issue by h4** [bem/bem-bl#398]
Например, тут: http://bem.github.io/bem-bl/sets/common-desktop/i-bem/i-bem.ru.html ни одна ссылка не работает. Приходится прокручивать всю портянку и вдумчиво разбираться. Или пользоваться Cmd+F

Причина, скорее всего в том, что якоря в *.wiki обёрнуты в `%%hl %%`

```
%%hl xml
<a name="abstract.blocks"></a>
%%
===== Блоки без DOM-представления
```

**Comment by deeonis** [comment]
Актуальная документация переехала на bem.info, этот issue закрываю за давностью
