### ISSUE TITLE
b-slider не работает в Android 2.3

### ISSUE THREAD

**Issue by metrofun** [bem/bem-bl#406]
При этом, если

realtimeSlide= ua.ios || ua.android >= '4' ||  ua.bada || ua.opera || ua.other || false,

поменять на 

realtimeSlide= ua.ios || ua.android >= '2' ||  ua.bada || ua.opera || ua.other;

Все начинает работать

**Comment by tadatuta** [comment]
cc @deepsweet

**Comment by deepsweet** [comment]
всё хитрее.
для Android < 4 реалтаймовый слайдер в силу убогости системы отключён, а ему на помощь должны подключаться вспомогательные b-slider-arrows.
если точно "начинает работать", то стоит проверить это на устройствах пяти.

**Comment by metrofun** [comment]
Да, я обратил на это внимание, когда проверял как работает на серпе ) Там уши.
Я проверял на HTC Desire HD, анимация работает более чем приемлемо.

**Comment by deepsweet** [comment]
там всё очень стрёмно, мы думали даже массив UA моделей делать.
тогдашняя половина нашего стенда на 2.х отказывалась внятно работать с реалтаймом, тупо из-за необъяснимых косяков с тач-событиями на уровне системы – типа если был тачстарт и после него тачмув, то тачэнд уже не триггерится.

**Comment by metrofun** [comment]
Может touchcancel тригерился? Может это связано с какой-то минорной версией ветки 2.3 андроида?
У нас (в Киеве) всего один девайс с андроидом 2.3, поэтому особенно поковырять не получается.

**Comment by deepsweet** [comment]
разница была именно в моделях, даже минорные версии совпадали полностью (и это, кстати, не единственный баг на андроидах с такими признаками).
завтра попробую проверить заново на каких-нибудь девайсах, которые найду.
но мне помнится, что не всё там чисто.

**Comment by deeonis** [comment]
Блок безнадежно устарел, как и этот issue, который висит полтора года. Закрываю его за давностью.
