### ISSUE TITLE
Add ability to instantiate DOM-based blocks from runtime...

### ISSUE THREAD

**Issue by GREENpoint** [bem/bem-bl#412]
Add ability to instantiate DOM-based blocks from runtime using BEM.DOM.create:
1. Easy to build OPA using bem-bl.
2. Easy to test DOM-base blocks.

**Comment by tadatuta** [comment]
you can instantiate DOM-based blocks by searching them in DOM with `findBlock*` methods or getting them by calling `.bem()` on jQuery chain:

``` javascript
$('.b-block').bem('b-block') // b-block will be initiated automatically
```

**Comment by GREENpoint** [comment]
Yep, I know. But it's long way:
1. Generate json
2. json -> html
3. Fill element with generated html
4. Use .bem to get JS-interface

It will be good solution to hide all this logic in this method:

var instance = BEM.DOM.create('my-ui-block');

**Comment by deeonis** [comment]
Unfortunately, we still haven't got enough resources to implement the proposed solution. Closing this issue over the period of limitation
