### ISSUE TITLE
npm.yandex-team.ru в npm-shrinkwrap 0.3

### ISSUE THREAD

**Issue by stanislav-mitkin** [bem/bem-bl#414]
Перестали устанавливаться зависимости для bem-bl @ 0.3 , из-за того, что в npm-shrinkwrap.json указаны урлы на http://npm.yandex-team.ru:5984

**Comment by tavriaforever** [comment]
Спасибо, пофиксим.

**Comment by tavriaforever** [comment]
fixed, tag 0.3.18
