### ISSUE TITLE
Зависимость блока b-link от block: 'i-bem', elems: ['html'] ломает генерацию html у блока b-page

### ISSUE THREAD

**Issue by alexbaumgertner** [bem/bem-bl#417]
Зависимость блока b-link https://github.com/bem/bem-bl/blob/0.3/blocks-desktop/b-link/b-link.deps.js ломает генерацию html для блока b-page

Как повторить: https://github.com/alexbaumgertner/bem-bl-b-link-bug

**Comment by tadatuta** [comment]
Твой проект использует библиотеку bemhtml, которую использовать не нужно.
Предполагаю, что если вместо нее использовать i-bem__html из bem-bl, все будет хорошо.

Если так, то задачу нужно закрыть, т.к. библиотека bemhtml не поддерживается и к использованию не рекомендуется.

**Comment by alexbaumgertner** [comment]
"Предполагаю, что если вместо нее использовать i-bem__html из bem-bl, все будет хорошо." -- а как это сделать?

**Comment by alexbaumgertner** [comment]
:ok:

**Comment by tadatuta** [comment]
@alexbaumgertner если вопрос по-прежнему актуален, то см. https://github.com/bem/project-stub в ветке master.
