### ISSUE TITLE
Release 1.0.0 version with apostol.BEM-1537.jq_plug_tap branch

### ISSUE THREAD

**Issue by alexbaumgertner** [bem/bem-bl#441]
Release 1.0.0 version with apostol.BEM-1537.jq_plug_tap branch
(https://github.com/bem/bem-bl/tree/apostol.BEM-1537.jq_plug_tap)

**Comment by alexbaumgertner** [comment]
//cc @truerenton @arikon

**Comment by alexbaumgertner** [comment]
//cc @SevInf

**Comment by SevInf** [comment]
#439 should be merged before release.

**Comment by tadatuta** [comment]
@alexbaumgertner дойду до Олега, сделаем.
