### ISSUE TITLE
Не вызывается деструктор динамически созданного блока

### ISSUE THREAD

**Issue by dosyara** [bem/bem-bl#498]
Я на DOM-ноде создаю блок следующим образом:
`new BEM.blocks[blockName](domElem, params);`

Создается инстанс блока, на ноде появляется класс blockName_js_inited
Далее, я удаляю эту ноду через `BEM.DOM.update` или через `destruct` другого блока, но деструктор моего созданного блока не вызывается.
Фидл с иллюстрацией http://jsfiddle.net/EsJYd/16/

**Comment by dfilatov** [comment]
Твой фидл немного некорректен: `this.destruct()` никогда не приводил к удалению другого блока на этой ноде.

**Comment by dfilatov** [comment]
А вот пример, иллюстрирующий проблему -- http://jsfiddle.net/9VYm9/

**Comment by dfilatov** [comment]
Кстати, если ты будешь создавать инстанс BEM.DOM-блока не через `new` (откуда взялся этот способ?), а через рекомендованный `domElem.bem('virt')`, то все будет нормально.

**Comment by dfilatov** [comment]
В пул-реквесте фиксится та проблема, про которую я думал изначально -- корректный деструкт блока, неявно созданного на DOM-ноде без css-класса i-bem.
