### ISSUE TITLE
Передача контекста блока внутрь функции для использования this.*

### ISSUE THREAD

**Issue by belyanskii** [bem/bem-bl#555]
При передаче контекста блока в функцию нам становится недоступен this.block/elem/mods/elemMods.

Пример подобного использования - https://github.com/belyanskii/waaat/blob/master/blocks/a/a.bemhtml

Коммит который приводит к проблеме - https://github.com/bem/bem-bl/commit/b7c74fdd1d9c87f4c84f22425ef926b7989c5b0d#diff-1e3b56f9e0e181c66b57850e6b506ed0L198

Воспроизвести проблему можно с помощью примера который находится тут - https://github.com/belyanskii/waaat

**Comment by indutny** [comment]
Should be fixed by https://github.com/bem/bem-bl/pull/560, could you please verify?

**Comment by belyanskii** [comment]
@indutny проверил с веткой из PR - в собранном bemhtml.js ничего не поменялось кажется и проблема остается. Если что - код для проверки тут, в bower.json просто можешь свою ветку ставить и смотреть :)

**Comment by indutny** [comment]
Это потому что ты используешь bem-bl-xjst, в нем есть своя копия bem-bl. Сейчас сделаю и туда PR.

**Comment by indutny** [comment]
https://github.com/bem/bem-bl-xjst/pull/5

**Comment by belyanskii** [comment]
@indutny - попробовал с bem-bl-xjst из ветки что в PR, тоже ничего не полетело, возможно еще что-нибудь надо поменять? (enb-xjst версию?)

**Comment by indutny** [comment]
Все ясно, у тебя теперь там другой пример :) Вопрос же был про чтение из `this`, а теперь ты туда пишешь и даже вызываешь apply. cc @veged

**Comment by belyanskii** [comment]
@indutny да, эту проблему тоже обсуждали и казалось что оно связанно

**Comment by veged** [comment]
там вроде только apply и вызывается? что мешает также сделать как и с чтением из this? если есть apply то прокидывать честный объект

**Comment by indutny** [comment]
@veged я придумал как сделать, скоро починим :)

**Comment by belyanskii** [comment]
@indutny ping :)

**Comment by belyanskii** [comment]
@indutny pong

**Comment by tadatuta** [comment]
@indutny Am I right that the fix should also be ported to `bem-xjst`?

**Comment by indutny** [comment]
I'd wait for a whole fix. Right now I have fixed only part of it in these commits and in https://github.com/veged/xjst/commit/e4cffd6c053a01dfb6e4c4e54a1b216cb5a563d7 . Going to finish this up tomorrow.

**Comment by indutny** [comment]
@belyanskii please give a try to latest: https://github.com/bem/bem-bl-xjst/pull/5

**Comment by belyanskii** [comment]
@indutny it's working!! brilliant!! @tadatuta, now i need new versions of library's :+1:

**Comment by tadatuta** [comment]
@indutny Fedor, will you release bem-bl-xjst yourself or should I do it while you're on vacation? :)
To do so I just need to know how destructive these changes are: should it be major version or patch will be enough? And should it be ported into support/1.x branch as well?

And what about `bem-xjst`? Do we need any changes there or weak deps on `xjst` is just enough?

**Comment by indutny** [comment]
@tadatuta I'll do it in a patch version, and yeah it should be ported.

**Comment by indutny** [comment]
@belyanskii released in bem-bl-xjst@2.0.3

**Comment by indutny** [comment]
@tadatuta ah, it seems like support/1.x is not affected, because it isn't using this optimisation.
