### ISSUE TITLE
i-ua.js, window.matchMedia returns null in hidden iframes

### ISSUE THREAD

**Issue by belyanskii** [bem/bem-bl#588]
Господа, в блоке i-ua есть https://github.com/bem/bem-bl/blob/v2.5.1/blocks-common/i-ua/i-ua.js#L23
Если это все будет выполнено в iframe который скрыт, то мы получим ошибку.

**Comment by tadatuta** [comment]
// cc @Andre-487

**Comment by andre487** [comment]
Подал реквест на исправление
