### ISSUE TITLE
Feedback for "i-bem.js: Руководство пользователя"

### ISSUE THREAD

**Issue by a-x-** [bem/bem-bl#596]
Не работает редактирование через prose.io или я что-то не так делаю.

Идёт вечная отправка реквеста изменений.

Примерный дифф того, что я хочу изменить:

``` diff
   Работа с модификаторами блока

   Модификатор задаёт блоку определённое состояние. Каждому блоку можно присвоить один 
   или несколько модификаторов (у блока также может не быть модификаторов вообще). У 
   модификатора есть имя и значение.
+  **Значение должно быть исключительно строкой**, неявное приведение типов не производится.
```

``` diff
   Расширение поведения

   В предыдущем примере код кастомизации полностью переопределяет поведение блока.       
   Технология bem-js позволяет также реализовывать «доопределение» блока. Для этого в    
-  методах кастомизирующего кода можно вызывать this._~_base.apply(), передавая в качестве 
+  методах кастомизирующего кода можно вызывать this.__base.apply(), передавая в качестве 
```

**Значение должно быть исключительно строкой**, неявное приведение типов не производится.

**Comment by tadatuta** [comment]
@a-x- Спасибо! Я удалил тильды, а фразу про строку решил все-таки не добавлять, т.к. тип параметров явно прописан в [JSDOC](http://ru.bem.info/libs/bem-bl/dev/desktop/i-bem/jsdoc/)

**Comment by a-x-** [comment]
Ok

Там кстати ещё в некоторых местах есть тильды _~_

А не знаете почему редактирование через `prose.io` глючит?

**Comment by tadatuta** [comment]
@a-x- у нас часть данных собирается на сайт из веток (их можно редактировать через prose.io), а часть — из тегов (и там не всегда очевидно, куда вносить изменения). нужно, конечно, доработать схему.
