### ISSUE TITLE
b-slider: слайдер при инициализации затирает наследуемую от i-bem__dom функцию

### ISSUE THREAD

**Issue by baymer** [bem/bem-bl#599]
переменная: https://github.com/baymer/bem-bl/blob/dev/blocks-touch/b-slider/b-slider.js#L121

метод: https://github.com/bem/bem-bl/blob/dev/blocks-common/i-bem/__dom/i-bem__dom.js#L825

**Comment by truerenton** [comment]
`_elem` не является методом BEM.DOM.
Уточни, что ты имеешь ввиду.

**Comment by deeonis** [comment]
BEM-2121

**Comment by xoxulin** [comment]
Fixed and created PR https://github.com/bem/bem-bl/pull/612

**Comment by YetiOr** [comment]
:+1:
