### ISSUE TITLE
Небольшая защита для удаленных блоков

### ISSUE THREAD

**Issue by mightyaleksey** [bem/bem-bl#643]
Привет, у меня часто возникает проблема в этом месте: https://github.com/bem/bem-bl/blob/support/2.x/blocks-common/i-bem/__dom/i-bem__dom.js#L773

Обычно, проблема возникает тут, когда я удаляю или устанавливаю новый модификатор на блоке (методы `setMod()`, `delMod()`), а блок уже к этому моменту удален.

Что вы думаете, если добавить в этом месте или чуть [выше](https://github.com/bem/bem-bl/blob/support/2.x/blocks-common/i-bem/i-bem.js#L351) отдельную проверку на `this.domElem`?

**Comment by mightyaleksey** [comment]
И сам текст ошибки:

``` bash
TypeError: 'undefined' is not an object (evaluating '(elem || this.domElem).each') (<some path>)
```

**Comment by narqo** [comment]
Кажется, #637 решит проблему.

/сс @dfilatov

**Comment by mightyaleksey** [comment]
Да, похоже на то, спасибо

**Comment by arikon** [comment]
Должно быть исправлено здесь https://github.com/bem/bem-bl/pull/648

Если нет — переоткройте.
