### ISSUE TITLE
html-doc for i-bem: link is broken

### ISSUE THREAD

**Issue by Flackus** [bem/bem-bl#66]
http://bem.github.com/bem-bl/sets/common-desktop/i-bem/i-bem.ru.html:

> Также существуют методы hasMod(), getMod/getMods(), toggleMod() и delMod(). 
> Сигнатуры этих методов доступны в референсе по BEM.

Link in the last sentence should point to https://github.com/bem/bem-bl/blob/master/blocks-common/i-bem/i-bem.js (I guess).

**Comment by deepsweet** [comment]
на i-bem.js не надо, мы просто почему-то не генерируем jsdoc.wiki

**Comment by deeonis** [comment]
Неактуально за давностью лет
